version: '3'
 
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: auction_user
      MYSQL_PASSWORD: auction_bot
    volumes:
      - dbdata:/var/lib/mysql
      - dbinit:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    container_name: pma2
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    environment:
      TZ: "Europe/Rome"
  app:
    image: asaku01/asaku_telegram_bot_auction:latest
    container_name: telegram_auction_bot
    environment:
      TBOT_TOKEN: 1805311871:AAFlXtOGhBzjFOvNhcTNwcMbEFuxZSp6Cx0
      DB_HOST: db
      DB_USER: auction_user
      DB_PASSWORD: auction_bot
      DB_DATABASE: auction_bot
      DB_PORT: 3306
    depends_on:
      db:
        condition: service_healthy
volumes:
  dbdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./db_data
  dbinit:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./db_init